//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public int code { get; set; }
        public string name { get; set; }
        public int type_id { get; set; }
        public string size { get; set; }
        public int size_type_id { get; set; }
        public int count { get; set; }
        public double price { get; set; }
        public byte active { get; set; }
    
        public virtual Type Type { get; set; }
        public virtual Type Type1 { get; set; }
    }
}
